disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - todo
  - force_cast
  - force_try
  - type_name
  - type_body_length
  - file_length
  - void_function_in_ternary
  - block_based_kvo
  - redundant_optional_initialization
  - multiple_closures_with_trailing_closure
  - line_length
  - for_where
  - class_delegate_protocol
  - unused_optional_binding
  - non_optional_string_data_conversion
  - opening_brace

opt_in_rules:
  - explicit_top_level_acl
  - explicit_acl
  - no_extension_access_modifier

identifier_name:
  allowed_symbols: _
  min_length: 1
  max_length: 75
  validates_start_with_lowercase: warning
  
#opening_brace:
#  allow_multiline_func: true

trailing_comma:
  mandatory_comma: true
  
nesting:
  type_level:
    warning: 3
    error: 4
