name: Bug report
description: Create a report to help us improve.
title: "🐞: "
labels: ["bug", "triage"]
assignees:
  - hpinhal
body:
  - type: markdown
    attributes:
      value: |
        Review your implementation against the [documentation](https://docs.notifica.re/) to filter out potential integration problems before creating an issue.
        Issues matching common integration problems will be directed to the appropriate documentation section and closed.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A list of clear steps to reproduce the behaviour.
      placeholder: |
        1. Do '...'
        2. ...
        3. Run into the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
  - type: markdown
    attributes:
      value: |
        ---
        ### Platform information
  - type: input
    attributes:
      label: Library version
      description: What version of our software are you running?
      placeholder: e.g. 3.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      description: What operating system are you testing with?
      placeholder: e.g. iOS 16
    validations:
      required: true
  - type: input
    attributes:
      label: Smartphone model
      description: What is the brand and model of your test device?
      placeholder: e.g. iPhone 14
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the problem here.
